require:
  - rubocop-rails

inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - '/spec/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'db/migrate/*.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'feature', 'scenario', 'let', 'it']
